# This is a basic workflow to help you get started with Actions

name: Deploy Virtual Machine TEST2

on:
  workflow_dispatch: 
    inputs: 
      resourceGroupName:
        description: Resource Group Name
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ジョブの名前
  deploy-virtual-machine:
    # ワークフローの実行環境の指定
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.resourceGroupName }}
